#!/bin/bash
export COLOR="\[\033[0;32m\]"

cd /tmp

echo -e "${COLOR}Upgrade system"; tput sgr0
sudo apt -y update
sudo apt -y dist-upgrade

echo -e "${COLOR}Install shit"; tput sgr0
sudo apt-get -y install build-essential fish htop yakuake tmux xclip ncdu mc vlc mpv ffmpeg vim keychain lm-sensors unrar transmission-qt i965-va-driver vainfo net-tools

echo -e "${COLOR}Download and install Dropbox"; tput sgr0
wget -O dropbox.deb https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
sudo dpkg -i dropbox.deb
sudo apt -y install -f

echo -e "${COLOR}Download and install Google Music Manager"; tput sgr0
wget https://dl.google.com/linux/direct/google-musicmanager-beta_current_amd64.deb
sudo dpkg -i google-musicmanager-beta_current_amd64.deb
sudo apt -y install -f

echo -e "${COLOR}Download and install Virtualbox"; tput sgr0
wget -O vbox.deb https://download.virtualbox.org/virtualbox/5.2.12/virtualbox-5.2_5.2.12-122591~Ubuntu~bionic_amd64.deb
sudo dpkg -i vbox.deb
sudo apt -y install -f

echo -e "${COLOR}Add PPA's"; tput sgr0
sudo add-apt-repository -y ppa:papirus/papirus
sudo add-apt-repository -y ppa:phoerious/keepassxc
sudo add-apt-repository -y ppa:tista/adapta
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo add-apt-repository -y ppa:alexlarsson/flatpak

echo -e "${COLOR}Install more shit"; tput sgr0
sudo apt-get -y install keepassxc adapta-gtk-theme streamlink flatpak adapta-kde kvantum papirus-icon-theme

ssh-keygen -f $HOME/.ssh/id_rsa -N ''
echo 'eval `keychain --eval id_rsa`' >> .bashrc

wget http://installer.jdownloader.org/JD2Setup_x64.sh
konsole -e "/bin/sh /tmp/JD2Setup_x64.sh"

