#!/bin/bash
export COLOR="\[\033[0;32m\]"

echo -e "${COLOR}Remove packages"; tput sgr0
cd /tmp
#sudo apt -y purge firefox* kwrite vim
#sudo apt -y autoremove

echo -e "${COLOR}Upgrade system"; tput sgr0
sudo apt -y update
sudo apt -y dist-upgrade

echo -e "${COLOR}Download and install Dropbox"; tput sgr0
wget -O dropbox.deb https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
sudo dpkg -i dropbox.deb 
sudo apt -y install -f

wget https://dl.opendesktop.org/api/files/downloadfile/id/1524079107/s/342bb017ce2d02ca0269b0fb6b3602c8/t/1526876716/u/19333/simplemenu-1.0.12.plasmoid
plasmapkg2 -i simplemenu-1.0.12.plasmoid 

echo -e "${COLOR}Add PPA's"; tput sgr0
sudo add-apt-repository -y ppa:papirus/papirus
sudo add-apt-repository -y ppa:phoerious/keepassxc
sudo apt-get -y update


sudo apt-get -y install --install-recommends adapta-kde

echo -e "${COLOR}Install shit"; tput sgr0
sudo apt-get -y install fish htop yakuake tmux xclip keepassxc 


if [[ $(grep bionic /etc/apt/sources.list | wc -c) -ne 0 ]]; then

  sudo add-apt-repository -y ppa:tista/adapta
  sudo apt-get -y update
  sudo apt-get -y install adapta-gtk-theme

fi
